pull_request_rules:
  - name: Automatic merge to master
    conditions:
      - '-draft'
      - '#approved-reviews-by>=1'
      - 'approved-reviews-by=@gestalt-core'
      - 'status-success~=^Test'
      - '#status-failure=0'
      - 'base=master'
    actions:
      merge:
        strict: true
        strict_method: rebase
        method: squash
        commit_message: title+body
