os:
  - linux
dist: trusty
language: node_js
node_js:
  - lts/carbon
addons:
  chrome: unstable
before_install:
  - yarn global add greenkeeper-lockfile@2
  - yarn global add codecov
before_script:
  - greenkeeper-lockfile-update
  - yarn danger ci

after_script:
  - greenkeeper-lockfile-upload
  - codecov
