#!/usr/bin/env bash
set -e
set -x

# export DISPLAY=:99.0
# if [[ -f /etc/init.d/xvfb ]]; then
#   /etc/init.d/xvfb start
# fi

(
  cd test && yarn webpack-dev-server --hot --inline --progress --colors
)
#  & (
#   cd test && BABEL_DISABLE_CACHE=1 NODE_ENV=testing yarn babel-node server.js
# ) &

# PID=$!                    # get the Parent Process ID
# PGID=$(ps opgid= "$PID")  # get the Process Group ID
#
# until $(curl --output /dev/null --silent --head --fail http://localhost:3000/__ping); do
#     printf '.'
#     sleep 5
# done
#
# total_chunks=${BUILDKITE_PARALLEL_JOB_COUNT:=1}
# this_chunk=$((${BUILDKITE_PARALLEL_JOB:=0} + 1))
#
# NODE_ENV=integration yarn ghostjs $(find packages/gestalt -name '*.ghost.js' | xargs node ./scripts/chunk.js ${total_chunks} ${this_chunk})
# STATUS=$?
#
# # Kill the process group and all children of that process group.
# kill -- -$PGID &> /dev/null
#
# exit $STATUS
