#!/usr/bin/env bash
set -euo pipefail

export DISPLAY=:99.0
if [[ -f /etc/init.d/xvfb ]]; then
  /etc/init.d/xvfb start
fi

yarn build

# Start the server
( cd test && yarn start ) &

PID=$! # get the Parent Process ID
PGID=$(ps opgid= "$PID") # get the Process Group ID

until $(curl --output /dev/null --silent --head --fail http://localhost:3000); do
    printf '.'
    sleep 5
done

JEST_PUPPETEER_CONFIG="scripts/jestPuppeteer.config.js" yarn jest --config scripts/jestIntegration.config.json
STATUS=$?

# Kill the process group and all children of that process group.
kill -- -$PGID &> /dev/null

exit $STATUS
