// flow-typed signature: 6caafb78a3ee556f596350e702049601
// flow-typed version: <<STUB>>/codecov_v^3.7.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'codecov'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'codecov' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'codecov/lib/codecov' {
  declare module.exports: any;
}

declare module 'codecov/lib/detect' {
  declare module.exports: any;
}

declare module 'codecov/lib/git' {
  declare module.exports: any;
}

declare module 'codecov/lib/offline' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/appveyor' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/azurePipelines' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/buildkite' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/circle' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/cirrus' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/codebuild' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/codeship' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/drone' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/gitlab' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/heroku' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/jenkins' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/localGit' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/semaphore' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/semaphore2x' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/shippable' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/snap' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/teamcity' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/travis' {
  declare module.exports: any;
}

declare module 'codecov/lib/services/wercker' {
  declare module.exports: any;
}

declare module 'codecov/test/detect.test' {
  declare module.exports: any;
}

declare module 'codecov/test/git.test' {
  declare module.exports: any;
}

declare module 'codecov/test/index.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/appveyor.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/azure-pipelines.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/buildkite.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/circle.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/cirrus.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/codebuild.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/codeship.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/drone.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/gitlab.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/heroku.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/jenkins.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/localGit.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/semaphore.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/semaphore2x.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/shippable.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/snap.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/teamcity.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/travis.test' {
  declare module.exports: any;
}

declare module 'codecov/test/services/wercker.test' {
  declare module.exports: any;
}

declare module 'codecov/test/upload.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'codecov/index' {
  declare module.exports: $Exports<'codecov'>;
}
declare module 'codecov/index.js' {
  declare module.exports: $Exports<'codecov'>;
}
declare module 'codecov/lib/codecov.js' {
  declare module.exports: $Exports<'codecov/lib/codecov'>;
}
declare module 'codecov/lib/detect.js' {
  declare module.exports: $Exports<'codecov/lib/detect'>;
}
declare module 'codecov/lib/git.js' {
  declare module.exports: $Exports<'codecov/lib/git'>;
}
declare module 'codecov/lib/offline.js' {
  declare module.exports: $Exports<'codecov/lib/offline'>;
}
declare module 'codecov/lib/services/appveyor.js' {
  declare module.exports: $Exports<'codecov/lib/services/appveyor'>;
}
declare module 'codecov/lib/services/azurePipelines.js' {
  declare module.exports: $Exports<'codecov/lib/services/azurePipelines'>;
}
declare module 'codecov/lib/services/buildkite.js' {
  declare module.exports: $Exports<'codecov/lib/services/buildkite'>;
}
declare module 'codecov/lib/services/circle.js' {
  declare module.exports: $Exports<'codecov/lib/services/circle'>;
}
declare module 'codecov/lib/services/cirrus.js' {
  declare module.exports: $Exports<'codecov/lib/services/cirrus'>;
}
declare module 'codecov/lib/services/codebuild.js' {
  declare module.exports: $Exports<'codecov/lib/services/codebuild'>;
}
declare module 'codecov/lib/services/codeship.js' {
  declare module.exports: $Exports<'codecov/lib/services/codeship'>;
}
declare module 'codecov/lib/services/drone.js' {
  declare module.exports: $Exports<'codecov/lib/services/drone'>;
}
declare module 'codecov/lib/services/gitlab.js' {
  declare module.exports: $Exports<'codecov/lib/services/gitlab'>;
}
declare module 'codecov/lib/services/heroku.js' {
  declare module.exports: $Exports<'codecov/lib/services/heroku'>;
}
declare module 'codecov/lib/services/jenkins.js' {
  declare module.exports: $Exports<'codecov/lib/services/jenkins'>;
}
declare module 'codecov/lib/services/localGit.js' {
  declare module.exports: $Exports<'codecov/lib/services/localGit'>;
}
declare module 'codecov/lib/services/semaphore.js' {
  declare module.exports: $Exports<'codecov/lib/services/semaphore'>;
}
declare module 'codecov/lib/services/semaphore2x.js' {
  declare module.exports: $Exports<'codecov/lib/services/semaphore2x'>;
}
declare module 'codecov/lib/services/shippable.js' {
  declare module.exports: $Exports<'codecov/lib/services/shippable'>;
}
declare module 'codecov/lib/services/snap.js' {
  declare module.exports: $Exports<'codecov/lib/services/snap'>;
}
declare module 'codecov/lib/services/teamcity.js' {
  declare module.exports: $Exports<'codecov/lib/services/teamcity'>;
}
declare module 'codecov/lib/services/travis.js' {
  declare module.exports: $Exports<'codecov/lib/services/travis'>;
}
declare module 'codecov/lib/services/wercker.js' {
  declare module.exports: $Exports<'codecov/lib/services/wercker'>;
}
declare module 'codecov/test/detect.test.js' {
  declare module.exports: $Exports<'codecov/test/detect.test'>;
}
declare module 'codecov/test/git.test.js' {
  declare module.exports: $Exports<'codecov/test/git.test'>;
}
declare module 'codecov/test/index.test.js' {
  declare module.exports: $Exports<'codecov/test/index.test'>;
}
declare module 'codecov/test/services/appveyor.test.js' {
  declare module.exports: $Exports<'codecov/test/services/appveyor.test'>;
}
declare module 'codecov/test/services/azure-pipelines.test.js' {
  declare module.exports: $Exports<'codecov/test/services/azure-pipelines.test'>;
}
declare module 'codecov/test/services/buildkite.test.js' {
  declare module.exports: $Exports<'codecov/test/services/buildkite.test'>;
}
declare module 'codecov/test/services/circle.test.js' {
  declare module.exports: $Exports<'codecov/test/services/circle.test'>;
}
declare module 'codecov/test/services/cirrus.test.js' {
  declare module.exports: $Exports<'codecov/test/services/cirrus.test'>;
}
declare module 'codecov/test/services/codebuild.test.js' {
  declare module.exports: $Exports<'codecov/test/services/codebuild.test'>;
}
declare module 'codecov/test/services/codeship.test.js' {
  declare module.exports: $Exports<'codecov/test/services/codeship.test'>;
}
declare module 'codecov/test/services/drone.test.js' {
  declare module.exports: $Exports<'codecov/test/services/drone.test'>;
}
declare module 'codecov/test/services/gitlab.test.js' {
  declare module.exports: $Exports<'codecov/test/services/gitlab.test'>;
}
declare module 'codecov/test/services/heroku.test.js' {
  declare module.exports: $Exports<'codecov/test/services/heroku.test'>;
}
declare module 'codecov/test/services/jenkins.test.js' {
  declare module.exports: $Exports<'codecov/test/services/jenkins.test'>;
}
declare module 'codecov/test/services/localGit.test.js' {
  declare module.exports: $Exports<'codecov/test/services/localGit.test'>;
}
declare module 'codecov/test/services/semaphore.test.js' {
  declare module.exports: $Exports<'codecov/test/services/semaphore.test'>;
}
declare module 'codecov/test/services/semaphore2x.test.js' {
  declare module.exports: $Exports<'codecov/test/services/semaphore2x.test'>;
}
declare module 'codecov/test/services/shippable.test.js' {
  declare module.exports: $Exports<'codecov/test/services/shippable.test'>;
}
declare module 'codecov/test/services/snap.test.js' {
  declare module.exports: $Exports<'codecov/test/services/snap.test'>;
}
declare module 'codecov/test/services/teamcity.test.js' {
  declare module.exports: $Exports<'codecov/test/services/teamcity.test'>;
}
declare module 'codecov/test/services/travis.test.js' {
  declare module.exports: $Exports<'codecov/test/services/travis.test'>;
}
declare module 'codecov/test/services/wercker.test.js' {
  declare module.exports: $Exports<'codecov/test/services/wercker.test'>;
}
declare module 'codecov/test/upload.test.js' {
  declare module.exports: $Exports<'codecov/test/upload.test'>;
}
