// flow-typed signature: d84ed504e1b5d4bc46d9a3c8b87abe09
// flow-typed version: <<STUB>>/css-modules-flow-types-cli_v^1.4.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-modules-flow-types-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-modules-flow-types-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'css-modules-flow-types-cli/bin/cli' {
  declare module.exports: any;
}

declare module 'css-modules-flow-types-cli/dist/__test__/converter.test' {
  declare module.exports: any;
}

declare module 'css-modules-flow-types-cli/dist/cli' {
  declare module.exports: any;
}

declare module 'css-modules-flow-types-cli/dist/converter' {
  declare module.exports: any;
}

declare module 'css-modules-flow-types-cli/dist/css-modules/fileSystemLoader' {
  declare module.exports: any;
}

declare module 'css-modules-flow-types-cli/dist/writer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'css-modules-flow-types-cli/bin/cli.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/bin/cli'>;
}
declare module 'css-modules-flow-types-cli/dist/__test__/converter.test.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/dist/__test__/converter.test'>;
}
declare module 'css-modules-flow-types-cli/dist/cli.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/dist/cli'>;
}
declare module 'css-modules-flow-types-cli/dist/converter.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/dist/converter'>;
}
declare module 'css-modules-flow-types-cli/dist/css-modules/fileSystemLoader.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/dist/css-modules/fileSystemLoader'>;
}
declare module 'css-modules-flow-types-cli/dist/writer.js' {
  declare module.exports: $Exports<'css-modules-flow-types-cli/dist/writer'>;
}
