// flow-typed signature: facf7d11962554af6e5931462b4d745a
// flow-typed version: <<STUB>>/cssnano_v^4.1.10/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssnano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssnano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssnano/dist' {
  declare module.exports: any;
}

declare module 'cssnano/quickstart' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssnano/dist/index' {
  declare module.exports: $Exports<'cssnano/dist'>;
}
declare module 'cssnano/dist/index.js' {
  declare module.exports: $Exports<'cssnano/dist'>;
}
declare module 'cssnano/quickstart.js' {
  declare module.exports: $Exports<'cssnano/quickstart'>;
}
