// flow-typed signature: 801da69d767e09da25afe6cb60115de5
// flow-typed version: <<STUB>>/husky_v^4.3.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'husky'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'husky' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'husky/bin/run' {
  declare module.exports: any;
}

declare module 'husky/husky' {
  declare module.exports: any;
}

declare module 'husky/lib/checkGitDirEnv' {
  declare module.exports: any;
}

declare module 'husky/lib/debug' {
  declare module.exports: any;
}

declare module 'husky/lib/getConf' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/bin' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/checkGitVersion' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/getBanner' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/gitRevParse' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/hooks' {
  declare module.exports: any;
}

declare module 'husky/lib/installer' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/is' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/localScript' {
  declare module.exports: any;
}

declare module 'husky/lib/installer/mainScript' {
  declare module.exports: any;
}

declare module 'husky/lib/read-pkg' {
  declare module.exports: any;
}

declare module 'husky/lib/runner/bin' {
  declare module.exports: any;
}

declare module 'husky/lib/runner' {
  declare module.exports: any;
}

declare module 'husky/lib/upgrader/bin' {
  declare module.exports: any;
}

declare module 'husky/lib/upgrader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'husky/bin/run.js' {
  declare module.exports: $Exports<'husky/bin/run'>;
}
declare module 'husky/husky.js' {
  declare module.exports: $Exports<'husky/husky'>;
}
declare module 'husky/lib/checkGitDirEnv.js' {
  declare module.exports: $Exports<'husky/lib/checkGitDirEnv'>;
}
declare module 'husky/lib/debug.js' {
  declare module.exports: $Exports<'husky/lib/debug'>;
}
declare module 'husky/lib/getConf.js' {
  declare module.exports: $Exports<'husky/lib/getConf'>;
}
declare module 'husky/lib/installer/bin.js' {
  declare module.exports: $Exports<'husky/lib/installer/bin'>;
}
declare module 'husky/lib/installer/checkGitVersion.js' {
  declare module.exports: $Exports<'husky/lib/installer/checkGitVersion'>;
}
declare module 'husky/lib/installer/getBanner.js' {
  declare module.exports: $Exports<'husky/lib/installer/getBanner'>;
}
declare module 'husky/lib/installer/gitRevParse.js' {
  declare module.exports: $Exports<'husky/lib/installer/gitRevParse'>;
}
declare module 'husky/lib/installer/hooks.js' {
  declare module.exports: $Exports<'husky/lib/installer/hooks'>;
}
declare module 'husky/lib/installer/index' {
  declare module.exports: $Exports<'husky/lib/installer'>;
}
declare module 'husky/lib/installer/index.js' {
  declare module.exports: $Exports<'husky/lib/installer'>;
}
declare module 'husky/lib/installer/is.js' {
  declare module.exports: $Exports<'husky/lib/installer/is'>;
}
declare module 'husky/lib/installer/localScript.js' {
  declare module.exports: $Exports<'husky/lib/installer/localScript'>;
}
declare module 'husky/lib/installer/mainScript.js' {
  declare module.exports: $Exports<'husky/lib/installer/mainScript'>;
}
declare module 'husky/lib/read-pkg.js' {
  declare module.exports: $Exports<'husky/lib/read-pkg'>;
}
declare module 'husky/lib/runner/bin.js' {
  declare module.exports: $Exports<'husky/lib/runner/bin'>;
}
declare module 'husky/lib/runner/index' {
  declare module.exports: $Exports<'husky/lib/runner'>;
}
declare module 'husky/lib/runner/index.js' {
  declare module.exports: $Exports<'husky/lib/runner'>;
}
declare module 'husky/lib/upgrader/bin.js' {
  declare module.exports: $Exports<'husky/lib/upgrader/bin'>;
}
declare module 'husky/lib/upgrader/index' {
  declare module.exports: $Exports<'husky/lib/upgrader'>;
}
declare module 'husky/lib/upgrader/index.js' {
  declare module.exports: $Exports<'husky/lib/upgrader'>;
}
