// flow-typed signature: cb6947e8dc04430f15dfb98229186fcc
// flow-typed version: <<STUB>>/lint-staged_v^10.3.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lint-staged/bin/lint-staged' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/chunkFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/execGit' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/file' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/generateTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/getRenderer' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/getStagedFiles' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/gitWorkflow' {
  declare module.exports: any;
}

declare module 'lint-staged/lib' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/makeCmdTasks' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/messages' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/printTaskOutput' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/resolveGitRepo' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/resolveTaskFn' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/runAll' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/state' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/symbols' {
  declare module.exports: any;
}

declare module 'lint-staged/lib/validateConfig' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lint-staged/bin/lint-staged.js' {
  declare module.exports: $Exports<'lint-staged/bin/lint-staged'>;
}
declare module 'lint-staged/lib/chunkFiles.js' {
  declare module.exports: $Exports<'lint-staged/lib/chunkFiles'>;
}
declare module 'lint-staged/lib/execGit.js' {
  declare module.exports: $Exports<'lint-staged/lib/execGit'>;
}
declare module 'lint-staged/lib/file.js' {
  declare module.exports: $Exports<'lint-staged/lib/file'>;
}
declare module 'lint-staged/lib/generateTasks.js' {
  declare module.exports: $Exports<'lint-staged/lib/generateTasks'>;
}
declare module 'lint-staged/lib/getRenderer.js' {
  declare module.exports: $Exports<'lint-staged/lib/getRenderer'>;
}
declare module 'lint-staged/lib/getStagedFiles.js' {
  declare module.exports: $Exports<'lint-staged/lib/getStagedFiles'>;
}
declare module 'lint-staged/lib/gitWorkflow.js' {
  declare module.exports: $Exports<'lint-staged/lib/gitWorkflow'>;
}
declare module 'lint-staged/lib/index' {
  declare module.exports: $Exports<'lint-staged/lib'>;
}
declare module 'lint-staged/lib/index.js' {
  declare module.exports: $Exports<'lint-staged/lib'>;
}
declare module 'lint-staged/lib/makeCmdTasks.js' {
  declare module.exports: $Exports<'lint-staged/lib/makeCmdTasks'>;
}
declare module 'lint-staged/lib/messages.js' {
  declare module.exports: $Exports<'lint-staged/lib/messages'>;
}
declare module 'lint-staged/lib/printTaskOutput.js' {
  declare module.exports: $Exports<'lint-staged/lib/printTaskOutput'>;
}
declare module 'lint-staged/lib/resolveGitRepo.js' {
  declare module.exports: $Exports<'lint-staged/lib/resolveGitRepo'>;
}
declare module 'lint-staged/lib/resolveTaskFn.js' {
  declare module.exports: $Exports<'lint-staged/lib/resolveTaskFn'>;
}
declare module 'lint-staged/lib/runAll.js' {
  declare module.exports: $Exports<'lint-staged/lib/runAll'>;
}
declare module 'lint-staged/lib/state.js' {
  declare module.exports: $Exports<'lint-staged/lib/state'>;
}
declare module 'lint-staged/lib/symbols.js' {
  declare module.exports: $Exports<'lint-staged/lib/symbols'>;
}
declare module 'lint-staged/lib/validateConfig.js' {
  declare module.exports: $Exports<'lint-staged/lib/validateConfig'>;
}
