// flow-typed signature: 20ed95d18d48ce1ed81e82ac75e1fe7f
// flow-typed version: <<STUB>>/loader-utils_v2.0.2/flow_v0.178.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loader-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loader-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loader-utils/lib/getCurrentRequest' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/getHashDigest' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/getOptions' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/getRemainingRequest' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/hash/BatchedHash' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/hash/md4' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/hash/wasm-hash' {
  declare module.exports: any;
}

declare module 'loader-utils/lib' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/interpolateName' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/isUrlRequest' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/parseQuery' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/parseString' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/stringifyRequest' {
  declare module.exports: any;
}

declare module 'loader-utils/lib/urlToRequest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loader-utils/lib/getCurrentRequest.js' {
  declare module.exports: $Exports<'loader-utils/lib/getCurrentRequest'>;
}
declare module 'loader-utils/lib/getHashDigest.js' {
  declare module.exports: $Exports<'loader-utils/lib/getHashDigest'>;
}
declare module 'loader-utils/lib/getOptions.js' {
  declare module.exports: $Exports<'loader-utils/lib/getOptions'>;
}
declare module 'loader-utils/lib/getRemainingRequest.js' {
  declare module.exports: $Exports<'loader-utils/lib/getRemainingRequest'>;
}
declare module 'loader-utils/lib/hash/BatchedHash.js' {
  declare module.exports: $Exports<'loader-utils/lib/hash/BatchedHash'>;
}
declare module 'loader-utils/lib/hash/md4.js' {
  declare module.exports: $Exports<'loader-utils/lib/hash/md4'>;
}
declare module 'loader-utils/lib/hash/wasm-hash.js' {
  declare module.exports: $Exports<'loader-utils/lib/hash/wasm-hash'>;
}
declare module 'loader-utils/lib/index' {
  declare module.exports: $Exports<'loader-utils/lib'>;
}
declare module 'loader-utils/lib/index.js' {
  declare module.exports: $Exports<'loader-utils/lib'>;
}
declare module 'loader-utils/lib/interpolateName.js' {
  declare module.exports: $Exports<'loader-utils/lib/interpolateName'>;
}
declare module 'loader-utils/lib/isUrlRequest.js' {
  declare module.exports: $Exports<'loader-utils/lib/isUrlRequest'>;
}
declare module 'loader-utils/lib/parseQuery.js' {
  declare module.exports: $Exports<'loader-utils/lib/parseQuery'>;
}
declare module 'loader-utils/lib/parseString.js' {
  declare module.exports: $Exports<'loader-utils/lib/parseString'>;
}
declare module 'loader-utils/lib/stringifyRequest.js' {
  declare module.exports: $Exports<'loader-utils/lib/stringifyRequest'>;
}
declare module 'loader-utils/lib/urlToRequest.js' {
  declare module.exports: $Exports<'loader-utils/lib/urlToRequest'>;
}
