// flow-typed signature: b32e33db0c0513bb1b0cd37a7ea18539
// flow-typed version: <<STUB>>/lottie-react_v2.3.1/flow_v0.187.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lottie-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lottie-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lottie-react/build/index.es' {
  declare module.exports: any;
}

declare module 'lottie-react/build/index.es.min' {
  declare module.exports: any;
}

declare module 'lottie-react/build' {
  declare module.exports: any;
}

declare module 'lottie-react/build/index.min' {
  declare module.exports: any;
}

declare module 'lottie-react/build/index.umd' {
  declare module.exports: any;
}

declare module 'lottie-react/build/index.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lottie-react/build/index.es.js' {
  declare module.exports: $Exports<'lottie-react/build/index.es'>;
}
declare module 'lottie-react/build/index.es.min.js' {
  declare module.exports: $Exports<'lottie-react/build/index.es.min'>;
}
declare module 'lottie-react/build/index' {
  declare module.exports: $Exports<'lottie-react/build'>;
}
declare module 'lottie-react/build/index.js' {
  declare module.exports: $Exports<'lottie-react/build'>;
}
declare module 'lottie-react/build/index.min.js' {
  declare module.exports: $Exports<'lottie-react/build/index.min'>;
}
declare module 'lottie-react/build/index.umd.js' {
  declare module.exports: $Exports<'lottie-react/build/index.umd'>;
}
declare module 'lottie-react/build/index.umd.min.js' {
  declare module.exports: $Exports<'lottie-react/build/index.umd.min'>;
}
