// flow-typed signature: d346b93af6972d1b001d0107f2f56aa6
// flow-typed version: <<STUB>>/lz-string_v^1.4.4/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lz-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lz-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'lz-string/bin/bin' {
  declare module.exports: any;
}

declare module 'lz-string/libs/base64-string' {
  declare module.exports: any;
}

declare module 'lz-string/libs/lz-string' {
  declare module.exports: any;
}

declare module 'lz-string/libs/lz-string.min' {
  declare module.exports: any;
}

declare module 'lz-string/reference/lz-string-1.0.2' {
  declare module.exports: any;
}

declare module 'lz-string/tests/lib/jasmine-1.3.1/jasmine-html' {
  declare module.exports: any;
}

declare module 'lz-string/tests/lib/jasmine-1.3.1/jasmine' {
  declare module.exports: any;
}

declare module 'lz-string/tests/lz-string-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'lz-string/bin/bin.js' {
  declare module.exports: $Exports<'lz-string/bin/bin'>;
}
declare module 'lz-string/libs/base64-string.js' {
  declare module.exports: $Exports<'lz-string/libs/base64-string'>;
}
declare module 'lz-string/libs/lz-string.js' {
  declare module.exports: $Exports<'lz-string/libs/lz-string'>;
}
declare module 'lz-string/libs/lz-string.min.js' {
  declare module.exports: $Exports<'lz-string/libs/lz-string.min'>;
}
declare module 'lz-string/reference/lz-string-1.0.2.js' {
  declare module.exports: $Exports<'lz-string/reference/lz-string-1.0.2'>;
}
declare module 'lz-string/tests/lib/jasmine-1.3.1/jasmine-html.js' {
  declare module.exports: $Exports<'lz-string/tests/lib/jasmine-1.3.1/jasmine-html'>;
}
declare module 'lz-string/tests/lib/jasmine-1.3.1/jasmine.js' {
  declare module.exports: $Exports<'lz-string/tests/lib/jasmine-1.3.1/jasmine'>;
}
declare module 'lz-string/tests/lz-string-spec.js' {
  declare module.exports: $Exports<'lz-string/tests/lz-string-spec'>;
}
