// flow-typed signature: 995194b9c5670b08c9d3bdbdf25c5b43
// flow-typed version: <<STUB>>/marked_v^0.8.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'marked'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'marked' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'marked/lib/marked.esm' {
  declare module.exports: any;
}

declare module 'marked/lib/marked' {
  declare module.exports: any;
}

declare module 'marked/marked.min' {
  declare module.exports: any;
}

declare module 'marked/src/defaults' {
  declare module.exports: any;
}

declare module 'marked/src/helpers' {
  declare module.exports: any;
}

declare module 'marked/src/InlineLexer' {
  declare module.exports: any;
}

declare module 'marked/src/Lexer' {
  declare module.exports: any;
}

declare module 'marked/src/marked' {
  declare module.exports: any;
}

declare module 'marked/src/Parser' {
  declare module.exports: any;
}

declare module 'marked/src/Renderer' {
  declare module.exports: any;
}

declare module 'marked/src/rules' {
  declare module.exports: any;
}

declare module 'marked/src/Slugger' {
  declare module.exports: any;
}

declare module 'marked/src/TextRenderer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'marked/lib/marked.esm.js' {
  declare module.exports: $Exports<'marked/lib/marked.esm'>;
}
declare module 'marked/lib/marked.js' {
  declare module.exports: $Exports<'marked/lib/marked'>;
}
declare module 'marked/marked.min.js' {
  declare module.exports: $Exports<'marked/marked.min'>;
}
declare module 'marked/src/defaults.js' {
  declare module.exports: $Exports<'marked/src/defaults'>;
}
declare module 'marked/src/helpers.js' {
  declare module.exports: $Exports<'marked/src/helpers'>;
}
declare module 'marked/src/InlineLexer.js' {
  declare module.exports: $Exports<'marked/src/InlineLexer'>;
}
declare module 'marked/src/Lexer.js' {
  declare module.exports: $Exports<'marked/src/Lexer'>;
}
declare module 'marked/src/marked.js' {
  declare module.exports: $Exports<'marked/src/marked'>;
}
declare module 'marked/src/Parser.js' {
  declare module.exports: $Exports<'marked/src/Parser'>;
}
declare module 'marked/src/Renderer.js' {
  declare module.exports: $Exports<'marked/src/Renderer'>;
}
declare module 'marked/src/rules.js' {
  declare module.exports: $Exports<'marked/src/rules'>;
}
declare module 'marked/src/Slugger.js' {
  declare module.exports: $Exports<'marked/src/Slugger'>;
}
declare module 'marked/src/TextRenderer.js' {
  declare module.exports: $Exports<'marked/src/TextRenderer'>;
}
