// flow-typed signature: 5bd5c41d8a129798e2dc8ba59b5ce770
// flow-typed version: <<STUB>>/netlify-cli_v^2.61.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'netlify-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'netlify-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'netlify-cli/scripts/postinstall' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons/auth' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons/config' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons/create' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons/delete' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/addons/list' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/api' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/build' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/deploy' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/dev/exec' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/dev' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env/get' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env/import' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env/list' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env/set' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/env/unset' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/functions/build' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/functions/create' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/functions' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/functions/invoke' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/functions/list' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/init' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/link' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/login' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/logout' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/open/admin' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/open' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/open/site' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/sites/config' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/sites/create' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/sites/delete' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/sites' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/sites/list' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/status/hooks' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/status' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/switch' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/unlink' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/commands/watch' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/angular' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/brunch' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/create-react-app' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/docusaurus' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/eleventy' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/ember' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/expo' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/gatsby' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/gridsome' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/hexo' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/hugo' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/jekyll' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/middleman' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/next' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/nuxt' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/parcel' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/phenomic' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/quasar-v0.17' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/quasar' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/react-static' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/sapper' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/stencil' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/svelte' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/utils/jsdetect' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/vue' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/detectors/vuepress' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/function-builder-detectors/netlify-lambda' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/apollo-graphql-rest/apollo-graphql-rest' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/apollo-graphql-rest/random-user' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/apollo-graphql/apollo-graphql' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/auth-fetch/auth-fetch' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/create-user/create-user' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/create-schema' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/create' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/delete' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/fauna-crud' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/read-all' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/read' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-crud/update' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-graphql/fauna-graphql' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/fauna-graphql/sync-schema' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/google-analytics/google-analytics' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/graphql-gateway' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/hasura-event-triggered/hasura-event-triggered' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/hello-world/hello-world' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/identity-signup/identity-signup' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/node-fetch/node-fetch' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/oauth-passport/oauth-passport' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/oauth-passport/utils/auth' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/oauth-passport/utils/config' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/protected-function/protected-function' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/sanity-create/sanity-create' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/sanity-groq/sanity-groq' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/send-email/send-email' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/send-email/validations' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/app' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-http' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-ssr' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/set-cookie/set-cookie' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/slack-rate-limit/slack-rate-limit' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/stripe-charge/stripe-charge' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/stripe-subscription/stripe-subscription' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/submission-created/submission-created' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/token-hider/token-hider' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/url-shortener/generate-route' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/url-shortener/get-route' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/url-shortener/url-shortener' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/functions-templates/js/using-middleware/using-middleware' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/hooks/analytics' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/hooks/init' {
  declare module.exports: any;
}

declare module 'netlify-cli/src' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/lib/exec-fetcher' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/lib/exec-fetcher.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/lib/settings' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/api' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/compare' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/diffs' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/diffs/options' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/prompts' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/render' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/addons/validation' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/chalk' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/check-command-inputs' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/command' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/create-stream-promise' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/detect-functions-builder' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/detect-server' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/detect-server.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/dev' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/env' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/env.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/finders' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/get-functions' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/get-functions.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/get-repo-data' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/gh-auth' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/gitignore' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/global-config' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/header' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/headers' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/headers.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/init/config-github' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/init/config-manual' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/init/netlify-toml-template' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/link/link-by-prompt' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/live-tunnel' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/logo' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/open-browser' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/parse-raw-flags' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/parse-raw-flags.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/proxy' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/read-repo-url' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/rules-proxy' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/rules-proxy.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/serve-functions' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/show-help' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/state-config' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/telemetry' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/telemetry/request' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/telemetry/validation' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/telemetry/validation.test' {
  declare module.exports: any;
}

declare module 'netlify-cli/src/utils/traffic-mesh' {
  declare module.exports: any;
}

// Filename aliases
declare module 'netlify-cli/scripts/postinstall.js' {
  declare module.exports: $Exports<'netlify-cli/scripts/postinstall'>;
}
declare module 'netlify-cli/src/commands/addons/auth.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons/auth'>;
}
declare module 'netlify-cli/src/commands/addons/config.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons/config'>;
}
declare module 'netlify-cli/src/commands/addons/create.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons/create'>;
}
declare module 'netlify-cli/src/commands/addons/delete.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons/delete'>;
}
declare module 'netlify-cli/src/commands/addons/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons'>;
}
declare module 'netlify-cli/src/commands/addons/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons'>;
}
declare module 'netlify-cli/src/commands/addons/list.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/addons/list'>;
}
declare module 'netlify-cli/src/commands/api.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/api'>;
}
declare module 'netlify-cli/src/commands/build/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/build'>;
}
declare module 'netlify-cli/src/commands/build/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/build'>;
}
declare module 'netlify-cli/src/commands/deploy.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/deploy'>;
}
declare module 'netlify-cli/src/commands/dev/exec.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/dev/exec'>;
}
declare module 'netlify-cli/src/commands/dev/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/dev'>;
}
declare module 'netlify-cli/src/commands/dev/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/dev'>;
}
declare module 'netlify-cli/src/commands/env/get.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env/get'>;
}
declare module 'netlify-cli/src/commands/env/import.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env/import'>;
}
declare module 'netlify-cli/src/commands/env/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env'>;
}
declare module 'netlify-cli/src/commands/env/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env'>;
}
declare module 'netlify-cli/src/commands/env/list.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env/list'>;
}
declare module 'netlify-cli/src/commands/env/set.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env/set'>;
}
declare module 'netlify-cli/src/commands/env/unset.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/env/unset'>;
}
declare module 'netlify-cli/src/commands/functions/build.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions/build'>;
}
declare module 'netlify-cli/src/commands/functions/create.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions/create'>;
}
declare module 'netlify-cli/src/commands/functions/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions'>;
}
declare module 'netlify-cli/src/commands/functions/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions'>;
}
declare module 'netlify-cli/src/commands/functions/invoke.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions/invoke'>;
}
declare module 'netlify-cli/src/commands/functions/list.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/functions/list'>;
}
declare module 'netlify-cli/src/commands/init.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/init'>;
}
declare module 'netlify-cli/src/commands/link.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/link'>;
}
declare module 'netlify-cli/src/commands/login.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/login'>;
}
declare module 'netlify-cli/src/commands/logout.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/logout'>;
}
declare module 'netlify-cli/src/commands/open/admin.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/open/admin'>;
}
declare module 'netlify-cli/src/commands/open/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/open'>;
}
declare module 'netlify-cli/src/commands/open/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/open'>;
}
declare module 'netlify-cli/src/commands/open/site.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/open/site'>;
}
declare module 'netlify-cli/src/commands/sites/config.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites/config'>;
}
declare module 'netlify-cli/src/commands/sites/create.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites/create'>;
}
declare module 'netlify-cli/src/commands/sites/delete.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites/delete'>;
}
declare module 'netlify-cli/src/commands/sites/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites'>;
}
declare module 'netlify-cli/src/commands/sites/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites'>;
}
declare module 'netlify-cli/src/commands/sites/list.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/sites/list'>;
}
declare module 'netlify-cli/src/commands/status/hooks.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/status/hooks'>;
}
declare module 'netlify-cli/src/commands/status/index' {
  declare module.exports: $Exports<'netlify-cli/src/commands/status'>;
}
declare module 'netlify-cli/src/commands/status/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/status'>;
}
declare module 'netlify-cli/src/commands/switch.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/switch'>;
}
declare module 'netlify-cli/src/commands/unlink.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/unlink'>;
}
declare module 'netlify-cli/src/commands/watch.js' {
  declare module.exports: $Exports<'netlify-cli/src/commands/watch'>;
}
declare module 'netlify-cli/src/detectors/angular.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/angular'>;
}
declare module 'netlify-cli/src/detectors/brunch.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/brunch'>;
}
declare module 'netlify-cli/src/detectors/create-react-app.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/create-react-app'>;
}
declare module 'netlify-cli/src/detectors/docusaurus.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/docusaurus'>;
}
declare module 'netlify-cli/src/detectors/eleventy.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/eleventy'>;
}
declare module 'netlify-cli/src/detectors/ember.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/ember'>;
}
declare module 'netlify-cli/src/detectors/expo.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/expo'>;
}
declare module 'netlify-cli/src/detectors/gatsby.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/gatsby'>;
}
declare module 'netlify-cli/src/detectors/gridsome.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/gridsome'>;
}
declare module 'netlify-cli/src/detectors/hexo.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/hexo'>;
}
declare module 'netlify-cli/src/detectors/hugo.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/hugo'>;
}
declare module 'netlify-cli/src/detectors/jekyll.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/jekyll'>;
}
declare module 'netlify-cli/src/detectors/middleman.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/middleman'>;
}
declare module 'netlify-cli/src/detectors/next.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/next'>;
}
declare module 'netlify-cli/src/detectors/nuxt.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/nuxt'>;
}
declare module 'netlify-cli/src/detectors/parcel.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/parcel'>;
}
declare module 'netlify-cli/src/detectors/phenomic.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/phenomic'>;
}
declare module 'netlify-cli/src/detectors/quasar-v0.17.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/quasar-v0.17'>;
}
declare module 'netlify-cli/src/detectors/quasar.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/quasar'>;
}
declare module 'netlify-cli/src/detectors/react-static.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/react-static'>;
}
declare module 'netlify-cli/src/detectors/sapper.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/sapper'>;
}
declare module 'netlify-cli/src/detectors/stencil.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/stencil'>;
}
declare module 'netlify-cli/src/detectors/svelte.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/svelte'>;
}
declare module 'netlify-cli/src/detectors/utils/jsdetect.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/utils/jsdetect'>;
}
declare module 'netlify-cli/src/detectors/vue.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/vue'>;
}
declare module 'netlify-cli/src/detectors/vuepress.js' {
  declare module.exports: $Exports<'netlify-cli/src/detectors/vuepress'>;
}
declare module 'netlify-cli/src/function-builder-detectors/netlify-lambda.js' {
  declare module.exports: $Exports<'netlify-cli/src/function-builder-detectors/netlify-lambda'>;
}
declare module 'netlify-cli/src/functions-templates/js/apollo-graphql-rest/apollo-graphql-rest.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/apollo-graphql-rest/apollo-graphql-rest'>;
}
declare module 'netlify-cli/src/functions-templates/js/apollo-graphql-rest/random-user.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/apollo-graphql-rest/random-user'>;
}
declare module 'netlify-cli/src/functions-templates/js/apollo-graphql/apollo-graphql.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/apollo-graphql/apollo-graphql'>;
}
declare module 'netlify-cli/src/functions-templates/js/auth-fetch/auth-fetch.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/auth-fetch/auth-fetch'>;
}
declare module 'netlify-cli/src/functions-templates/js/create-user/create-user.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/create-user/create-user'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/create-schema.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/create-schema'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/create.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/create'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/delete.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/delete'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/fauna-crud.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/fauna-crud'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/read-all.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/read-all'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/read.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/read'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-crud/update.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-crud/update'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-graphql/fauna-graphql.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-graphql/fauna-graphql'>;
}
declare module 'netlify-cli/src/functions-templates/js/fauna-graphql/sync-schema.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/fauna-graphql/sync-schema'>;
}
declare module 'netlify-cli/src/functions-templates/js/google-analytics/google-analytics.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/google-analytics/google-analytics'>;
}
declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-1'>;
}
declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/graphql-gateway/example-sibling-function-graphql-2'>;
}
declare module 'netlify-cli/src/functions-templates/js/graphql-gateway/graphql-gateway.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/graphql-gateway/graphql-gateway'>;
}
declare module 'netlify-cli/src/functions-templates/js/hasura-event-triggered/hasura-event-triggered.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/hasura-event-triggered/hasura-event-triggered'>;
}
declare module 'netlify-cli/src/functions-templates/js/hello-world/hello-world.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/hello-world/hello-world'>;
}
declare module 'netlify-cli/src/functions-templates/js/identity-signup/identity-signup.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/identity-signup/identity-signup'>;
}
declare module 'netlify-cli/src/functions-templates/js/node-fetch/node-fetch.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/node-fetch/node-fetch'>;
}
declare module 'netlify-cli/src/functions-templates/js/oauth-passport/oauth-passport.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/oauth-passport/oauth-passport'>;
}
declare module 'netlify-cli/src/functions-templates/js/oauth-passport/utils/auth.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/oauth-passport/utils/auth'>;
}
declare module 'netlify-cli/src/functions-templates/js/oauth-passport/utils/config.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/oauth-passport/utils/config'>;
}
declare module 'netlify-cli/src/functions-templates/js/protected-function/protected-function.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/protected-function/protected-function'>;
}
declare module 'netlify-cli/src/functions-templates/js/sanity-create/sanity-create.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/sanity-create/sanity-create'>;
}
declare module 'netlify-cli/src/functions-templates/js/sanity-groq/sanity-groq.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/sanity-groq/sanity-groq'>;
}
declare module 'netlify-cli/src/functions-templates/js/send-email/send-email.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/send-email/send-email'>;
}
declare module 'netlify-cli/src/functions-templates/js/send-email/validations.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/send-email/validations'>;
}
declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/app/index' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/serverless-ssr/app'>;
}
declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/app/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/serverless-ssr/app'>;
}
declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-http.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-http'>;
}
declare module 'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-ssr.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/serverless-ssr/serverless-ssr'>;
}
declare module 'netlify-cli/src/functions-templates/js/set-cookie/set-cookie.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/set-cookie/set-cookie'>;
}
declare module 'netlify-cli/src/functions-templates/js/slack-rate-limit/slack-rate-limit.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/slack-rate-limit/slack-rate-limit'>;
}
declare module 'netlify-cli/src/functions-templates/js/stripe-charge/stripe-charge.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/stripe-charge/stripe-charge'>;
}
declare module 'netlify-cli/src/functions-templates/js/stripe-subscription/stripe-subscription.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/stripe-subscription/stripe-subscription'>;
}
declare module 'netlify-cli/src/functions-templates/js/submission-created/submission-created.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/submission-created/submission-created'>;
}
declare module 'netlify-cli/src/functions-templates/js/token-hider/token-hider.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/token-hider/token-hider'>;
}
declare module 'netlify-cli/src/functions-templates/js/url-shortener/generate-route.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/url-shortener/generate-route'>;
}
declare module 'netlify-cli/src/functions-templates/js/url-shortener/get-route.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/url-shortener/get-route'>;
}
declare module 'netlify-cli/src/functions-templates/js/url-shortener/url-shortener.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/url-shortener/url-shortener'>;
}
declare module 'netlify-cli/src/functions-templates/js/using-middleware/using-middleware.js' {
  declare module.exports: $Exports<'netlify-cli/src/functions-templates/js/using-middleware/using-middleware'>;
}
declare module 'netlify-cli/src/hooks/analytics.js' {
  declare module.exports: $Exports<'netlify-cli/src/hooks/analytics'>;
}
declare module 'netlify-cli/src/hooks/init.js' {
  declare module.exports: $Exports<'netlify-cli/src/hooks/init'>;
}
declare module 'netlify-cli/src/index' {
  declare module.exports: $Exports<'netlify-cli/src'>;
}
declare module 'netlify-cli/src/index.js' {
  declare module.exports: $Exports<'netlify-cli/src'>;
}
declare module 'netlify-cli/src/lib/exec-fetcher.js' {
  declare module.exports: $Exports<'netlify-cli/src/lib/exec-fetcher'>;
}
declare module 'netlify-cli/src/lib/exec-fetcher.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/lib/exec-fetcher.test'>;
}
declare module 'netlify-cli/src/lib/settings.js' {
  declare module.exports: $Exports<'netlify-cli/src/lib/settings'>;
}
declare module 'netlify-cli/src/utils/addons.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons'>;
}
declare module 'netlify-cli/src/utils/addons/api.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/api'>;
}
declare module 'netlify-cli/src/utils/addons/compare.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/compare'>;
}
declare module 'netlify-cli/src/utils/addons/diffs/index' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/diffs'>;
}
declare module 'netlify-cli/src/utils/addons/diffs/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/diffs'>;
}
declare module 'netlify-cli/src/utils/addons/diffs/options.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/diffs/options'>;
}
declare module 'netlify-cli/src/utils/addons/prompts.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/prompts'>;
}
declare module 'netlify-cli/src/utils/addons/render.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/render'>;
}
declare module 'netlify-cli/src/utils/addons/validation.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/addons/validation'>;
}
declare module 'netlify-cli/src/utils/chalk.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/chalk'>;
}
declare module 'netlify-cli/src/utils/check-command-inputs.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/check-command-inputs'>;
}
declare module 'netlify-cli/src/utils/command.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/command'>;
}
declare module 'netlify-cli/src/utils/create-stream-promise.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/create-stream-promise'>;
}
declare module 'netlify-cli/src/utils/detect-functions-builder.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/detect-functions-builder'>;
}
declare module 'netlify-cli/src/utils/detect-server.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/detect-server'>;
}
declare module 'netlify-cli/src/utils/detect-server.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/detect-server.test'>;
}
declare module 'netlify-cli/src/utils/dev.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/dev'>;
}
declare module 'netlify-cli/src/utils/env.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/env'>;
}
declare module 'netlify-cli/src/utils/env.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/env.test'>;
}
declare module 'netlify-cli/src/utils/finders.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/finders'>;
}
declare module 'netlify-cli/src/utils/get-functions.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/get-functions'>;
}
declare module 'netlify-cli/src/utils/get-functions.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/get-functions.test'>;
}
declare module 'netlify-cli/src/utils/get-repo-data.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/get-repo-data'>;
}
declare module 'netlify-cli/src/utils/gh-auth.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/gh-auth'>;
}
declare module 'netlify-cli/src/utils/gitignore.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/gitignore'>;
}
declare module 'netlify-cli/src/utils/global-config.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/global-config'>;
}
declare module 'netlify-cli/src/utils/header.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/header'>;
}
declare module 'netlify-cli/src/utils/headers.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/headers'>;
}
declare module 'netlify-cli/src/utils/headers.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/headers.test'>;
}
declare module 'netlify-cli/src/utils/init/config-github.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/init/config-github'>;
}
declare module 'netlify-cli/src/utils/init/config-manual.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/init/config-manual'>;
}
declare module 'netlify-cli/src/utils/init/netlify-toml-template.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/init/netlify-toml-template'>;
}
declare module 'netlify-cli/src/utils/link/link-by-prompt.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/link/link-by-prompt'>;
}
declare module 'netlify-cli/src/utils/live-tunnel.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/live-tunnel'>;
}
declare module 'netlify-cli/src/utils/logo.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/logo'>;
}
declare module 'netlify-cli/src/utils/open-browser.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/open-browser'>;
}
declare module 'netlify-cli/src/utils/parse-raw-flags.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/parse-raw-flags'>;
}
declare module 'netlify-cli/src/utils/parse-raw-flags.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/parse-raw-flags.test'>;
}
declare module 'netlify-cli/src/utils/proxy.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/proxy'>;
}
declare module 'netlify-cli/src/utils/read-repo-url.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/read-repo-url'>;
}
declare module 'netlify-cli/src/utils/rules-proxy.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/rules-proxy'>;
}
declare module 'netlify-cli/src/utils/rules-proxy.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/rules-proxy.test'>;
}
declare module 'netlify-cli/src/utils/serve-functions.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/serve-functions'>;
}
declare module 'netlify-cli/src/utils/show-help.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/show-help'>;
}
declare module 'netlify-cli/src/utils/state-config.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/state-config'>;
}
declare module 'netlify-cli/src/utils/telemetry/index' {
  declare module.exports: $Exports<'netlify-cli/src/utils/telemetry'>;
}
declare module 'netlify-cli/src/utils/telemetry/index.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/telemetry'>;
}
declare module 'netlify-cli/src/utils/telemetry/request.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/telemetry/request'>;
}
declare module 'netlify-cli/src/utils/telemetry/validation.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/telemetry/validation'>;
}
declare module 'netlify-cli/src/utils/telemetry/validation.test.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/telemetry/validation.test'>;
}
declare module 'netlify-cli/src/utils/traffic-mesh.js' {
  declare module.exports: $Exports<'netlify-cli/src/utils/traffic-mesh'>;
}
