// flow-typed signature: e0f87719ae93c233d0be81e9326e9756
// flow-typed version: <<STUB>>/playwright_v1.37.1/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'playwright'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'playwright' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'playwright/cli' {
  declare module.exports: any;
}

declare module 'playwright/install' {
  declare module.exports: any;
}

// Filename aliases
declare module 'playwright/cli.js' {
  declare module.exports: $Exports<'playwright/cli'>;
}
declare module 'playwright/index' {
  declare module.exports: $Exports<'playwright'>;
}
declare module 'playwright/index.js' {
  declare module.exports: $Exports<'playwright'>;
}
declare module 'playwright/install.js' {
  declare module.exports: $Exports<'playwright/install'>;
}
