// flow-typed signature: 59c3e1b9096fce0d2ca0dc8aaf8894f0
// flow-typed version: <<STUB>>/react-lazy-hydration_v0.1.0/flow_v0.187.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-lazy-hydration'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-lazy-hydration' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-lazy-hydration/dist/index.browser.esm' {
  declare module.exports: any;
}

declare module 'react-lazy-hydration/dist/index.browser' {
  declare module.exports: any;
}

declare module 'react-lazy-hydration/dist/index.esm' {
  declare module.exports: any;
}

declare module 'react-lazy-hydration/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-lazy-hydration/dist/index.browser.esm.js' {
  declare module.exports: $Exports<'react-lazy-hydration/dist/index.browser.esm'>;
}
declare module 'react-lazy-hydration/dist/index.browser.js' {
  declare module.exports: $Exports<'react-lazy-hydration/dist/index.browser'>;
}
declare module 'react-lazy-hydration/dist/index.esm.js' {
  declare module.exports: $Exports<'react-lazy-hydration/dist/index.esm'>;
}
declare module 'react-lazy-hydration/dist/index' {
  declare module.exports: $Exports<'react-lazy-hydration/dist'>;
}
declare module 'react-lazy-hydration/dist/index.js' {
  declare module.exports: $Exports<'react-lazy-hydration/dist'>;
}
