// flow-typed signature: f9643d4940252d358bcfd77397ad1830
// flow-typed version: <<STUB>>/react-live_v^2.2.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-live'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-live' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-live/dist/react-live.cjs' {
  declare module.exports: any;
}

declare module 'react-live/dist/react-live.es' {
  declare module.exports: any;
}

declare module 'react-live/dist/react-live' {
  declare module.exports: any;
}

declare module 'react-live/dist/react-live.min' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Editor' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveContext' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveEditor' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveError' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LivePreview' {
  declare module.exports: any;
}

declare module 'react-live/src/components/Live/LiveProvider' {
  declare module.exports: any;
}

declare module 'react-live/src/constants/theme' {
  declare module.exports: any;
}

declare module 'react-live/src/hoc/withLive' {
  declare module.exports: any;
}

declare module 'react-live/src' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/errorBoundary.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/test/transpile.test' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/errorBoundary' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/evalCode' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile' {
  declare module.exports: any;
}

declare module 'react-live/src/utils/transpile/transform' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-live/dist/react-live.cjs.js' {
  declare module.exports: $Exports<'react-live/dist/react-live.cjs'>;
}
declare module 'react-live/dist/react-live.es.js' {
  declare module.exports: $Exports<'react-live/dist/react-live.es'>;
}
declare module 'react-live/dist/react-live.js' {
  declare module.exports: $Exports<'react-live/dist/react-live'>;
}
declare module 'react-live/dist/react-live.min.js' {
  declare module.exports: $Exports<'react-live/dist/react-live.min'>;
}
declare module 'react-live/src/components/Editor/index' {
  declare module.exports: $Exports<'react-live/src/components/Editor'>;
}
declare module 'react-live/src/components/Editor/index.js' {
  declare module.exports: $Exports<'react-live/src/components/Editor'>;
}
declare module 'react-live/src/components/Live/LiveContext.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveContext'>;
}
declare module 'react-live/src/components/Live/LiveEditor.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveEditor'>;
}
declare module 'react-live/src/components/Live/LiveError.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveError'>;
}
declare module 'react-live/src/components/Live/LivePreview.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LivePreview'>;
}
declare module 'react-live/src/components/Live/LiveProvider.js' {
  declare module.exports: $Exports<'react-live/src/components/Live/LiveProvider'>;
}
declare module 'react-live/src/constants/theme.js' {
  declare module.exports: $Exports<'react-live/src/constants/theme'>;
}
declare module 'react-live/src/hoc/withLive.js' {
  declare module.exports: $Exports<'react-live/src/hoc/withLive'>;
}
declare module 'react-live/src/index' {
  declare module.exports: $Exports<'react-live/src'>;
}
declare module 'react-live/src/index.js' {
  declare module.exports: $Exports<'react-live/src'>;
}
declare module 'react-live/src/utils/test/errorBoundary.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/errorBoundary.test'>;
}
declare module 'react-live/src/utils/test/transpile.test.js' {
  declare module.exports: $Exports<'react-live/src/utils/test/transpile.test'>;
}
declare module 'react-live/src/utils/transpile/errorBoundary.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/errorBoundary'>;
}
declare module 'react-live/src/utils/transpile/evalCode.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/evalCode'>;
}
declare module 'react-live/src/utils/transpile/index' {
  declare module.exports: $Exports<'react-live/src/utils/transpile'>;
}
declare module 'react-live/src/utils/transpile/index.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile'>;
}
declare module 'react-live/src/utils/transpile/transform.js' {
  declare module.exports: $Exports<'react-live/src/utils/transpile/transform'>;
}
