// flow-typed signature: 1f282d907363951f954e101e6dbf4eb5
// flow-typed version: <<STUB>>/rollup_v^2.26.11/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup/dist/es/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/es/shared/watch' {
  declare module.exports: any;
}

declare module 'rollup/dist/loadConfigFile' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup.browser' {
  declare module.exports: any;
}

declare module 'rollup/dist/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/loadConfigFile' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/mergeOptions' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/rollup' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/watch-cli' {
  declare module.exports: any;
}

declare module 'rollup/dist/shared/watch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup/dist/es/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/es/rollup.browser'>;
}
declare module 'rollup/dist/es/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/es/rollup'>;
}
declare module 'rollup/dist/es/shared/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/rollup'>;
}
declare module 'rollup/dist/es/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/es/shared/watch'>;
}
declare module 'rollup/dist/loadConfigFile.js' {
  declare module.exports: $Exports<'rollup/dist/loadConfigFile'>;
}
declare module 'rollup/dist/rollup.browser.js' {
  declare module.exports: $Exports<'rollup/dist/rollup.browser'>;
}
declare module 'rollup/dist/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/rollup'>;
}
declare module 'rollup/dist/shared/index' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/index.js' {
  declare module.exports: $Exports<'rollup/dist/shared'>;
}
declare module 'rollup/dist/shared/loadConfigFile.js' {
  declare module.exports: $Exports<'rollup/dist/shared/loadConfigFile'>;
}
declare module 'rollup/dist/shared/mergeOptions.js' {
  declare module.exports: $Exports<'rollup/dist/shared/mergeOptions'>;
}
declare module 'rollup/dist/shared/rollup.js' {
  declare module.exports: $Exports<'rollup/dist/shared/rollup'>;
}
declare module 'rollup/dist/shared/watch-cli.js' {
  declare module.exports: $Exports<'rollup/dist/shared/watch-cli'>;
}
declare module 'rollup/dist/shared/watch.js' {
  declare module.exports: $Exports<'rollup/dist/shared/watch'>;
}
