// flow-typed signature: 018d244e8f1eb5ffee6143347e1b6fd0
// flow-typed version: <<STUB>>/rollup-plugin-inline-svg_v^2.0.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rollup-plugin-inline-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'rollup-plugin-inline-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg.es2015' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/constants/Regexes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/createSvg' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/escapeQuotes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/extractAttributes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/hasAttribute' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/hasNode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/inlineNode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/placeAttributes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/removeForbiddenNode' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/removeSVGTagAttrs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/removeTagAttrs' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/removeTags' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/validateSvgAttributes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src/functions/validateSvgNodes' {
  declare module.exports: any;
}

declare module 'rollup-plugin-inline-svg/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg.es2015.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg.es2015'>;
}
declare module 'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/dist/rollup-plugin-inline-svg'>;
}
declare module 'rollup-plugin-inline-svg/src/constants/Regexes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/constants/Regexes'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/createSvg.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/createSvg'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/escapeQuotes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/escapeQuotes'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/extractAttributes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/extractAttributes'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/hasAttribute.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/hasAttribute'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/hasNode.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/hasNode'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/inlineNode.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/inlineNode'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/placeAttributes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/placeAttributes'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/removeForbiddenNode.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/removeForbiddenNode'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/removeSVGTagAttrs.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/removeSVGTagAttrs'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/removeTagAttrs.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/removeTagAttrs'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/removeTags.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/removeTags'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/validateSvgAttributes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/validateSvgAttributes'>;
}
declare module 'rollup-plugin-inline-svg/src/functions/validateSvgNodes.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src/functions/validateSvgNodes'>;
}
declare module 'rollup-plugin-inline-svg/src/index' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src'>;
}
declare module 'rollup-plugin-inline-svg/src/index.js' {
  declare module.exports: $Exports<'rollup-plugin-inline-svg/src'>;
}
