// flow-typed signature: c689a66efbdd70a1debbea272ea8d05a
// flow-typed version: <<STUB>>/stylelint-order_v^4.1.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-order'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-order' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-order/rules/checkAlphabeticalOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/calcAtRulePatternPriority' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/calcRulePatternPriority' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/checkNode' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/checkOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/createOrderInfo' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/getDescription' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/getOrderData' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/messages' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/ruleName' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/order/validatePrimaryOption' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-alphabetical-order/checkNode' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-alphabetical-order' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/addEmptyLineBefore' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/checkEmptyLineBefore' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/checkEmptyLineBeforeFirstProp' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/checkNodeForEmptyLines' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/checkNodeForOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/checkOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/createFlatOrder' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/createOrderInfo' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/getNodeData' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/hasEmptyLineBefore' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/messages' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/removeEmptyLinesBefore' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/ruleName' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/properties-order/validatePrimaryOption' {
  declare module.exports: any;
}

declare module 'stylelint-order/rules/shorthandData' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/getContainingNode' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isAtVariable' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isCustomProperty' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isDollarVariable' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isLessMixin' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isProperty' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isRuleWithNodes' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/isStandardSyntaxProperty' {
  declare module.exports: any;
}

declare module 'stylelint-order/utils/namespace' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-order/index' {
  declare module.exports: $Exports<'stylelint-order'>;
}
declare module 'stylelint-order/index.js' {
  declare module.exports: $Exports<'stylelint-order'>;
}
declare module 'stylelint-order/rules/checkAlphabeticalOrder.js' {
  declare module.exports: $Exports<'stylelint-order/rules/checkAlphabeticalOrder'>;
}
declare module 'stylelint-order/rules/index' {
  declare module.exports: $Exports<'stylelint-order/rules'>;
}
declare module 'stylelint-order/rules/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules'>;
}
declare module 'stylelint-order/rules/order/calcAtRulePatternPriority.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/calcAtRulePatternPriority'>;
}
declare module 'stylelint-order/rules/order/calcRulePatternPriority.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/calcRulePatternPriority'>;
}
declare module 'stylelint-order/rules/order/checkNode.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/checkNode'>;
}
declare module 'stylelint-order/rules/order/checkOrder.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/checkOrder'>;
}
declare module 'stylelint-order/rules/order/createOrderInfo.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/createOrderInfo'>;
}
declare module 'stylelint-order/rules/order/getDescription.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/getDescription'>;
}
declare module 'stylelint-order/rules/order/getOrderData.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/getOrderData'>;
}
declare module 'stylelint-order/rules/order/index' {
  declare module.exports: $Exports<'stylelint-order/rules/order'>;
}
declare module 'stylelint-order/rules/order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order'>;
}
declare module 'stylelint-order/rules/order/messages.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/messages'>;
}
declare module 'stylelint-order/rules/order/ruleName.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/ruleName'>;
}
declare module 'stylelint-order/rules/order/validatePrimaryOption.js' {
  declare module.exports: $Exports<'stylelint-order/rules/order/validatePrimaryOption'>;
}
declare module 'stylelint-order/rules/properties-alphabetical-order/checkNode.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-alphabetical-order/checkNode'>;
}
declare module 'stylelint-order/rules/properties-alphabetical-order/index' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-alphabetical-order'>;
}
declare module 'stylelint-order/rules/properties-alphabetical-order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-alphabetical-order'>;
}
declare module 'stylelint-order/rules/properties-order/addEmptyLineBefore.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/addEmptyLineBefore'>;
}
declare module 'stylelint-order/rules/properties-order/checkEmptyLineBefore.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/checkEmptyLineBefore'>;
}
declare module 'stylelint-order/rules/properties-order/checkEmptyLineBeforeFirstProp.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/checkEmptyLineBeforeFirstProp'>;
}
declare module 'stylelint-order/rules/properties-order/checkNodeForEmptyLines.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/checkNodeForEmptyLines'>;
}
declare module 'stylelint-order/rules/properties-order/checkNodeForOrder.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/checkNodeForOrder'>;
}
declare module 'stylelint-order/rules/properties-order/checkOrder.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/checkOrder'>;
}
declare module 'stylelint-order/rules/properties-order/createFlatOrder.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/createFlatOrder'>;
}
declare module 'stylelint-order/rules/properties-order/createOrderInfo.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/createOrderInfo'>;
}
declare module 'stylelint-order/rules/properties-order/getNodeData.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/getNodeData'>;
}
declare module 'stylelint-order/rules/properties-order/hasEmptyLineBefore.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/hasEmptyLineBefore'>;
}
declare module 'stylelint-order/rules/properties-order/index' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order'>;
}
declare module 'stylelint-order/rules/properties-order/index.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order'>;
}
declare module 'stylelint-order/rules/properties-order/messages.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/messages'>;
}
declare module 'stylelint-order/rules/properties-order/removeEmptyLinesBefore.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/removeEmptyLinesBefore'>;
}
declare module 'stylelint-order/rules/properties-order/ruleName.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/ruleName'>;
}
declare module 'stylelint-order/rules/properties-order/validatePrimaryOption.js' {
  declare module.exports: $Exports<'stylelint-order/rules/properties-order/validatePrimaryOption'>;
}
declare module 'stylelint-order/rules/shorthandData.js' {
  declare module.exports: $Exports<'stylelint-order/rules/shorthandData'>;
}
declare module 'stylelint-order/utils/getContainingNode.js' {
  declare module.exports: $Exports<'stylelint-order/utils/getContainingNode'>;
}
declare module 'stylelint-order/utils/index' {
  declare module.exports: $Exports<'stylelint-order/utils'>;
}
declare module 'stylelint-order/utils/index.js' {
  declare module.exports: $Exports<'stylelint-order/utils'>;
}
declare module 'stylelint-order/utils/isAtVariable.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isAtVariable'>;
}
declare module 'stylelint-order/utils/isCustomProperty.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isCustomProperty'>;
}
declare module 'stylelint-order/utils/isDollarVariable.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isDollarVariable'>;
}
declare module 'stylelint-order/utils/isLessMixin.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isLessMixin'>;
}
declare module 'stylelint-order/utils/isProperty.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isProperty'>;
}
declare module 'stylelint-order/utils/isRuleWithNodes.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isRuleWithNodes'>;
}
declare module 'stylelint-order/utils/isStandardSyntaxProperty.js' {
  declare module.exports: $Exports<'stylelint-order/utils/isStandardSyntaxProperty'>;
}
declare module 'stylelint-order/utils/namespace.js' {
  declare module.exports: $Exports<'stylelint-order/utils/namespace'>;
}
