// flow-typed signature: be576637d37f793b8eab2f302471c6e7
// flow-typed version: <<STUB>>/style-dictionary_v3.0.1/flow_v0.187.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'style-dictionary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'style-dictionary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'style-dictionary/examples/advanced/component-cti/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/App.test' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-app/src/serviceWorker' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/__tests__/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/babel.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/metro.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/src/App' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-file-header/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-formats-with-templates/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-parser/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/custom-transforms/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/format-helpers/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/matching-build-files/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/matching-build-files/tokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/multi-brand-multi-platform/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/s3/upload' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/tokens-deprecation/build' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/transitive-transforms/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/variables-in-outputs/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/examples/advanced/yaml-tokens/sd.config' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/buildAllPlatforms' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/buildFile' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/buildFiles' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/buildPlatform' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanActions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanAllPlatforms' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanDir' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanDirs' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanFile' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanFiles' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/cleanPlatform' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/actions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/createPropertyFormatter' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/fileHeader' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/formattedVariables' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/iconsWithPrefix' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/minifyDictionary' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/sortByName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formatHelpers/sortByReference' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/formats' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/transformGroups' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/common/transforms' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/exportPlatform' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/extend' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/filterProperties' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/performActions' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/action' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/fileHeader' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/filter' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/format' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/parser' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/template' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/transform' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/register/transformGroup' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/config' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/object' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/property' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/transform/propertySetup' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/combineJSON' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/convertToBase64' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/createDictionary' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/createFormatArgs' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/deepExtend' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/es6_' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/flattenProperties' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/groupMessages' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/createReferenceRegex' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/defaults' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getPathFromName' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/getReferences' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/resolveReference' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/references/usesReference' {
  declare module.exports: any;
}

declare module 'style-dictionary/lib/utils/resolveObject' {
  declare module.exports: any;
}

// Filename aliases
declare module 'style-dictionary/examples/advanced/component-cti/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/component-cti/config'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/App.test.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/App.test'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-css-modules/ComponentWithCssModules'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-sass/ComponentWithSass'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/components/with-styled-components/ComponentWithStyledComponents'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src'>;
}
declare module 'style-dictionary/examples/advanced/create-react-app/src/serviceWorker.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-app/src/serviceWorker'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/__tests__/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/__tests__/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/babel.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/babel.config'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/metro.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/metro.config'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/src/App.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/src/App'>;
}
declare module 'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/create-react-native-app/src/style-dictionary-dist/variables'>;
}
declare module 'style-dictionary/examples/advanced/custom-file-header/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-file-header/build'>;
}
declare module 'style-dictionary/examples/advanced/custom-formats-with-templates/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-formats-with-templates/build'>;
}
declare module 'style-dictionary/examples/advanced/custom-parser/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-parser/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/custom-transforms/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/custom-transforms/build'>;
}
declare module 'style-dictionary/examples/advanced/format-helpers/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/format-helpers/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/config'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/tokens/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/tokens'>;
}
declare module 'style-dictionary/examples/advanced/matching-build-files/tokens/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/matching-build-files/tokens'>;
}
declare module 'style-dictionary/examples/advanced/multi-brand-multi-platform/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/multi-brand-multi-platform/build'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/base'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/primary'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/button/secondary'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/components'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/config'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/background'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/border'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/brand'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/core'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/font'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/color'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/border'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/font'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/index' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/index.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size'>;
}
declare module 'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/node-modules-as-config-and-properties/tokens/size/padding'>;
}
declare module 'style-dictionary/examples/advanced/s3/upload.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/s3/upload'>;
}
declare module 'style-dictionary/examples/advanced/tokens-deprecation/build.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/tokens-deprecation/build'>;
}
declare module 'style-dictionary/examples/advanced/transitive-transforms/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/transitive-transforms/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/variables-in-outputs/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/variables-in-outputs/sd.config'>;
}
declare module 'style-dictionary/examples/advanced/yaml-tokens/sd.config.js' {
  declare module.exports: $Exports<'style-dictionary/examples/advanced/yaml-tokens/sd.config'>;
}
declare module 'style-dictionary/index' {
  declare module.exports: $Exports<'style-dictionary'>;
}
declare module 'style-dictionary/index.js' {
  declare module.exports: $Exports<'style-dictionary'>;
}
declare module 'style-dictionary/lib/buildAllPlatforms.js' {
  declare module.exports: $Exports<'style-dictionary/lib/buildAllPlatforms'>;
}
declare module 'style-dictionary/lib/buildFile.js' {
  declare module.exports: $Exports<'style-dictionary/lib/buildFile'>;
}
declare module 'style-dictionary/lib/buildFiles.js' {
  declare module.exports: $Exports<'style-dictionary/lib/buildFiles'>;
}
declare module 'style-dictionary/lib/buildPlatform.js' {
  declare module.exports: $Exports<'style-dictionary/lib/buildPlatform'>;
}
declare module 'style-dictionary/lib/cleanActions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanActions'>;
}
declare module 'style-dictionary/lib/cleanAllPlatforms.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanAllPlatforms'>;
}
declare module 'style-dictionary/lib/cleanDir.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanDir'>;
}
declare module 'style-dictionary/lib/cleanDirs.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanDirs'>;
}
declare module 'style-dictionary/lib/cleanFile.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanFile'>;
}
declare module 'style-dictionary/lib/cleanFiles.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanFiles'>;
}
declare module 'style-dictionary/lib/cleanPlatform.js' {
  declare module.exports: $Exports<'style-dictionary/lib/cleanPlatform'>;
}
declare module 'style-dictionary/lib/common/actions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/actions'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/createPropertyFormatter.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/createPropertyFormatter'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/fileHeader.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/fileHeader'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/formattedVariables.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/formattedVariables'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/iconsWithPrefix.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/iconsWithPrefix'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/index' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/index.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/minifyDictionary.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/minifyDictionary'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/sortByName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/sortByName'>;
}
declare module 'style-dictionary/lib/common/formatHelpers/sortByReference.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formatHelpers/sortByReference'>;
}
declare module 'style-dictionary/lib/common/formats.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/formats'>;
}
declare module 'style-dictionary/lib/common/transformGroups.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/transformGroups'>;
}
declare module 'style-dictionary/lib/common/transforms.js' {
  declare module.exports: $Exports<'style-dictionary/lib/common/transforms'>;
}
declare module 'style-dictionary/lib/exportPlatform.js' {
  declare module.exports: $Exports<'style-dictionary/lib/exportPlatform'>;
}
declare module 'style-dictionary/lib/extend.js' {
  declare module.exports: $Exports<'style-dictionary/lib/extend'>;
}
declare module 'style-dictionary/lib/filterProperties.js' {
  declare module.exports: $Exports<'style-dictionary/lib/filterProperties'>;
}
declare module 'style-dictionary/lib/performActions.js' {
  declare module.exports: $Exports<'style-dictionary/lib/performActions'>;
}
declare module 'style-dictionary/lib/register/action.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/action'>;
}
declare module 'style-dictionary/lib/register/fileHeader.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/fileHeader'>;
}
declare module 'style-dictionary/lib/register/filter.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/filter'>;
}
declare module 'style-dictionary/lib/register/format.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/format'>;
}
declare module 'style-dictionary/lib/register/parser.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/parser'>;
}
declare module 'style-dictionary/lib/register/template.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/template'>;
}
declare module 'style-dictionary/lib/register/transform.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/transform'>;
}
declare module 'style-dictionary/lib/register/transformGroup.js' {
  declare module.exports: $Exports<'style-dictionary/lib/register/transformGroup'>;
}
declare module 'style-dictionary/lib/transform/config.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/config'>;
}
declare module 'style-dictionary/lib/transform/object.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/object'>;
}
declare module 'style-dictionary/lib/transform/property.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/property'>;
}
declare module 'style-dictionary/lib/transform/propertySetup.js' {
  declare module.exports: $Exports<'style-dictionary/lib/transform/propertySetup'>;
}
declare module 'style-dictionary/lib/utils/combineJSON.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/combineJSON'>;
}
declare module 'style-dictionary/lib/utils/convertToBase64.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/convertToBase64'>;
}
declare module 'style-dictionary/lib/utils/createDictionary.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/createDictionary'>;
}
declare module 'style-dictionary/lib/utils/createFormatArgs.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/createFormatArgs'>;
}
declare module 'style-dictionary/lib/utils/deepExtend.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/deepExtend'>;
}
declare module 'style-dictionary/lib/utils/es6_.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/es6_'>;
}
declare module 'style-dictionary/lib/utils/flattenProperties.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/flattenProperties'>;
}
declare module 'style-dictionary/lib/utils/groupMessages.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/groupMessages'>;
}
declare module 'style-dictionary/lib/utils/references/createReferenceRegex.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/createReferenceRegex'>;
}
declare module 'style-dictionary/lib/utils/references/defaults.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/defaults'>;
}
declare module 'style-dictionary/lib/utils/references/getName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getName'>;
}
declare module 'style-dictionary/lib/utils/references/getPathFromName.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getPathFromName'>;
}
declare module 'style-dictionary/lib/utils/references/getReferences.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/getReferences'>;
}
declare module 'style-dictionary/lib/utils/references/resolveReference.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/resolveReference'>;
}
declare module 'style-dictionary/lib/utils/references/usesReference.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/references/usesReference'>;
}
declare module 'style-dictionary/lib/utils/resolveObject.js' {
  declare module.exports: $Exports<'style-dictionary/lib/utils/resolveObject'>;
}
