// flow-typed signature: 669c2ae0574c05531a2a62c316ca4bc4
// flow-typed version: <<STUB>>/tesseract.js_v5.0.4/flow_v0.216.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tesseract.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'tesseract.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tesseract.js/dist/tesseract.esm.min' {
  declare module.exports: any;
}

declare module 'tesseract.js/dist/tesseract.min' {
  declare module.exports: any;
}

declare module 'tesseract.js/dist/worker.min' {
  declare module.exports: any;
}

declare module 'tesseract.js/examples/node/download-pdf' {
  declare module.exports: any;
}

declare module 'tesseract.js/examples/node/image-processing' {
  declare module.exports: any;
}

declare module 'tesseract.js/examples/node/recognize' {
  declare module.exports: any;
}

declare module 'tesseract.js/examples/node/scheduler' {
  declare module.exports: any;
}

declare module 'tesseract.js/scripts/server' {
  declare module.exports: any;
}

declare module 'tesseract.js/scripts/test-helper' {
  declare module.exports: any;
}

declare module 'tesseract.js/scripts/webpack.config.common' {
  declare module.exports: any;
}

declare module 'tesseract.js/scripts/webpack.config.prod' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/constants/defaultOptions' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/constants/imageType' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/constants/languages' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/constants/OEM' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/constants/PSM' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/createJob' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/createScheduler' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/createWorker' {
  declare module.exports: any;
}

declare module 'tesseract.js/src' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/Tesseract' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/utils/circularize' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/utils/getEnvironment' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/utils/getId' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/utils/log' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/utils/resolvePaths' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/browser/cache' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/browser/getCore' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/browser/gunzip' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/browser' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/constants/defaultOutput' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/constants/defaultParams' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/node/cache' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/node/getCore' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/node/gunzip' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/node' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/utils/arrayBufferToBase64' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/utils/dump' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker-script/utils/setImage' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/defaultOptions' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/loadImage' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/onMessage' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/send' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/spawnWorker' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/browser/terminateWorker' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/defaultOptions' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/loadImage' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/onMessage' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/send' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/spawnWorker' {
  declare module.exports: any;
}

declare module 'tesseract.js/src/worker/node/terminateWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tesseract.js/dist/tesseract.esm.min.js' {
  declare module.exports: $Exports<'tesseract.js/dist/tesseract.esm.min'>;
}
declare module 'tesseract.js/dist/tesseract.min.js' {
  declare module.exports: $Exports<'tesseract.js/dist/tesseract.min'>;
}
declare module 'tesseract.js/dist/worker.min.js' {
  declare module.exports: $Exports<'tesseract.js/dist/worker.min'>;
}
declare module 'tesseract.js/examples/node/download-pdf.js' {
  declare module.exports: $Exports<'tesseract.js/examples/node/download-pdf'>;
}
declare module 'tesseract.js/examples/node/image-processing.js' {
  declare module.exports: $Exports<'tesseract.js/examples/node/image-processing'>;
}
declare module 'tesseract.js/examples/node/recognize.js' {
  declare module.exports: $Exports<'tesseract.js/examples/node/recognize'>;
}
declare module 'tesseract.js/examples/node/scheduler.js' {
  declare module.exports: $Exports<'tesseract.js/examples/node/scheduler'>;
}
declare module 'tesseract.js/scripts/server.js' {
  declare module.exports: $Exports<'tesseract.js/scripts/server'>;
}
declare module 'tesseract.js/scripts/test-helper.js' {
  declare module.exports: $Exports<'tesseract.js/scripts/test-helper'>;
}
declare module 'tesseract.js/scripts/webpack.config.common.js' {
  declare module.exports: $Exports<'tesseract.js/scripts/webpack.config.common'>;
}
declare module 'tesseract.js/scripts/webpack.config.prod.js' {
  declare module.exports: $Exports<'tesseract.js/scripts/webpack.config.prod'>;
}
declare module 'tesseract.js/src/constants/defaultOptions.js' {
  declare module.exports: $Exports<'tesseract.js/src/constants/defaultOptions'>;
}
declare module 'tesseract.js/src/constants/imageType.js' {
  declare module.exports: $Exports<'tesseract.js/src/constants/imageType'>;
}
declare module 'tesseract.js/src/constants/languages.js' {
  declare module.exports: $Exports<'tesseract.js/src/constants/languages'>;
}
declare module 'tesseract.js/src/constants/OEM.js' {
  declare module.exports: $Exports<'tesseract.js/src/constants/OEM'>;
}
declare module 'tesseract.js/src/constants/PSM.js' {
  declare module.exports: $Exports<'tesseract.js/src/constants/PSM'>;
}
declare module 'tesseract.js/src/createJob.js' {
  declare module.exports: $Exports<'tesseract.js/src/createJob'>;
}
declare module 'tesseract.js/src/createScheduler.js' {
  declare module.exports: $Exports<'tesseract.js/src/createScheduler'>;
}
declare module 'tesseract.js/src/createWorker.js' {
  declare module.exports: $Exports<'tesseract.js/src/createWorker'>;
}
declare module 'tesseract.js/src/index' {
  declare module.exports: $Exports<'tesseract.js/src'>;
}
declare module 'tesseract.js/src/index.js' {
  declare module.exports: $Exports<'tesseract.js/src'>;
}
declare module 'tesseract.js/src/Tesseract.js' {
  declare module.exports: $Exports<'tesseract.js/src/Tesseract'>;
}
declare module 'tesseract.js/src/utils/circularize.js' {
  declare module.exports: $Exports<'tesseract.js/src/utils/circularize'>;
}
declare module 'tesseract.js/src/utils/getEnvironment.js' {
  declare module.exports: $Exports<'tesseract.js/src/utils/getEnvironment'>;
}
declare module 'tesseract.js/src/utils/getId.js' {
  declare module.exports: $Exports<'tesseract.js/src/utils/getId'>;
}
declare module 'tesseract.js/src/utils/log.js' {
  declare module.exports: $Exports<'tesseract.js/src/utils/log'>;
}
declare module 'tesseract.js/src/utils/resolvePaths.js' {
  declare module.exports: $Exports<'tesseract.js/src/utils/resolvePaths'>;
}
declare module 'tesseract.js/src/worker-script/browser/cache.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/browser/cache'>;
}
declare module 'tesseract.js/src/worker-script/browser/getCore.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/browser/getCore'>;
}
declare module 'tesseract.js/src/worker-script/browser/gunzip.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/browser/gunzip'>;
}
declare module 'tesseract.js/src/worker-script/browser/index' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/browser'>;
}
declare module 'tesseract.js/src/worker-script/browser/index.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/browser'>;
}
declare module 'tesseract.js/src/worker-script/constants/defaultOutput.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/constants/defaultOutput'>;
}
declare module 'tesseract.js/src/worker-script/constants/defaultParams.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/constants/defaultParams'>;
}
declare module 'tesseract.js/src/worker-script/index' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script'>;
}
declare module 'tesseract.js/src/worker-script/index.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script'>;
}
declare module 'tesseract.js/src/worker-script/node/cache.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/node/cache'>;
}
declare module 'tesseract.js/src/worker-script/node/getCore.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/node/getCore'>;
}
declare module 'tesseract.js/src/worker-script/node/gunzip.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/node/gunzip'>;
}
declare module 'tesseract.js/src/worker-script/node/index' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/node'>;
}
declare module 'tesseract.js/src/worker-script/node/index.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/node'>;
}
declare module 'tesseract.js/src/worker-script/utils/arrayBufferToBase64.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/utils/arrayBufferToBase64'>;
}
declare module 'tesseract.js/src/worker-script/utils/dump.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/utils/dump'>;
}
declare module 'tesseract.js/src/worker-script/utils/setImage.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker-script/utils/setImage'>;
}
declare module 'tesseract.js/src/worker/browser/defaultOptions.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/defaultOptions'>;
}
declare module 'tesseract.js/src/worker/browser/index' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser'>;
}
declare module 'tesseract.js/src/worker/browser/index.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser'>;
}
declare module 'tesseract.js/src/worker/browser/loadImage.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/loadImage'>;
}
declare module 'tesseract.js/src/worker/browser/onMessage.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/onMessage'>;
}
declare module 'tesseract.js/src/worker/browser/send.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/send'>;
}
declare module 'tesseract.js/src/worker/browser/spawnWorker.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/spawnWorker'>;
}
declare module 'tesseract.js/src/worker/browser/terminateWorker.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/browser/terminateWorker'>;
}
declare module 'tesseract.js/src/worker/node/defaultOptions.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/defaultOptions'>;
}
declare module 'tesseract.js/src/worker/node/index' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node'>;
}
declare module 'tesseract.js/src/worker/node/index.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node'>;
}
declare module 'tesseract.js/src/worker/node/loadImage.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/loadImage'>;
}
declare module 'tesseract.js/src/worker/node/onMessage.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/onMessage'>;
}
declare module 'tesseract.js/src/worker/node/send.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/send'>;
}
declare module 'tesseract.js/src/worker/node/spawnWorker.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/spawnWorker'>;
}
declare module 'tesseract.js/src/worker/node/terminateWorker.js' {
  declare module.exports: $Exports<'tesseract.js/src/worker/node/terminateWorker'>;
}
