// flow-typed signature: 908350b8ac0184df648cc2948fd7ed27
// flow-typed version: <<STUB>>/universal-cookie_v4.0.0/flow_v0.162.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-cookie'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-cookie' {
  declare type Cookies = {
    cookies: {
      [string]: string,
    },
    ...
  };

  declare module.exports: (string) => Cookies;
}
