// flow-typed signature: 99ad234e68bd27f1f84fbb6a669a84f4
// flow-typed version: <<STUB>>/@babel/preset-flow_v^7.10.4/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/preset-flow'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/preset-flow' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/preset-flow/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/preset-flow/lib/index' {
  declare module.exports: $Exports<'@babel/preset-flow/lib'>;
}
declare module '@babel/preset-flow/lib/index.js' {
  declare module.exports: $Exports<'@babel/preset-flow/lib'>;
}
