steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: gestalt
        image-repository: 053722134931.dkr.ecr.us-east-1.amazonaws.com/pinterest
    agents:
      queue: elastic-builders
  - wait
  - name: ":jest: Test"
    command: ./scripts/test.sh
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
    env:
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PROJECT_SLUG
      - CODECOV_TOKEN
  - name: ":zap: danger"
    command: yarn danger ci
    timeout_in_minutes: 10
    env:
      - BUILDKITE
      - BUILDKITE_API_TOKEN
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - CI
      - DANGER_GITHUB_API_TOKEN
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
