steps:
  - name: ":docker: :package:"
    plugins:
      docker-compose:
        build: gestalt
        image-repository: 053722134931.dkr.ecr.us-east-1.amazonaws.com/pinterest
    agents:
      queue: elastic-builders
  - wait
  - name: ":hammer_and_wrench: build"
    command: yarn build
    artifact_paths: 'dist/stats.json'
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
  - wait
  - name: ":eslint:"
    command: yarn lint:js
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
  - name: ":stylelint:"
    command: yarn lint:css
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
  - name: ":flowtype:"
    command: yarn flow check
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
  - name: ":jest: Test"
    command: ./.buildkite/steps/test.sh
    timeout_in_minutes: 10
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
    env:
      - BUILDKITE_BRANCH
      - BUILDKITE_BUILD_NUMBER
      - BUILDKITE_BUILD_URL
      - BUILDKITE_COMMIT
      - BUILDKITE_PROJECT_SLUG
      - CODECOV_TOKEN
  - name: ":ghost: integration %n"
    command: ./run_integration_tests
    artifact_paths: 'screenshots/*'
    timeout_in_minutes: 30
    parallelism: 3
    env:
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PARALLEL_JOB_COUNT
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
  - name: ":zap: danger"
    command: yarn danger ci
    timeout_in_minutes: 10
    env:
      - BUILDKITE
      - BUILDKITE_API_TOKEN
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_REPO
      - CI
      - DANGER_GITHUB_API_TOKEN
    agents:
      queue: elastic
    plugins:
      docker-compose:
        run: gestalt
