const optionsFileHeaderOutputReferences = {
  'options': {
    'fileHeader': 'fileHeader',
    '_fileHeader_comment': 'Custom',
    'showFileHeader': true,
    'outputReferences': true,
  },
};

const optionsFileHeader = {
  'options': {
    'fileHeader': 'fileHeader',
    '_fileHeader_comment': 'Custom',
    'showFileHeader': true,
  },
};

function registerFileHeaders(sd) {
  sd.registerFileHeader({
    name: 'fileHeader',
    fileHeader: (defaultMessage) => ['File is autogenerated', ...defaultMessage],
  });
}

module.exports = { registerFileHeaders, optionsFileHeader, optionsFileHeaderOutputReferences };
