// flow-typed signature: 27530b14a1bc56829e2197619bda2a8c
// flow-typed version: <<STUB>>/@testing-library/react-hooks_v3.4.1/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react-hooks'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react-hooks' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react-hooks/dont-cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/asyncUtils' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/cleanup' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/flush-microtasks' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/lib/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src/asyncUtils' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src/cleanup' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src/flush-microtasks' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src' {
  declare module.exports: any;
}

declare module '@testing-library/react-hooks/src/pure' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react-hooks/dont-cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/dont-cleanup-after-each'>;
}
declare module '@testing-library/react-hooks/lib/asyncUtils.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/asyncUtils'>;
}
declare module '@testing-library/react-hooks/lib/cleanup.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/cleanup'>;
}
declare module '@testing-library/react-hooks/lib/flush-microtasks.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/flush-microtasks'>;
}
declare module '@testing-library/react-hooks/lib/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/lib/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib'>;
}
declare module '@testing-library/react-hooks/lib/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/lib/pure'>;
}
declare module '@testing-library/react-hooks/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/pure'>;
}
declare module '@testing-library/react-hooks/src/asyncUtils.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src/asyncUtils'>;
}
declare module '@testing-library/react-hooks/src/cleanup.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src/cleanup'>;
}
declare module '@testing-library/react-hooks/src/flush-microtasks.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src/flush-microtasks'>;
}
declare module '@testing-library/react-hooks/src/index' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src'>;
}
declare module '@testing-library/react-hooks/src/index.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src'>;
}
declare module '@testing-library/react-hooks/src/pure.js' {
  declare module.exports: $Exports<'@testing-library/react-hooks/src/pure'>;
}
