// flow-typed signature: cf9600555f25c805ddd62b5054326bb5
// flow-typed version: <<STUB>>/@testing-library/react_v^11.0.2/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@testing-library/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@testing-library/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@testing-library/react/dist/@testing-library/react.cjs' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.esm' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.pure.cjs' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.pure.esm' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.pure.umd' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.pure.umd.min' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.umd' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/@testing-library/react.umd.min' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/act-compat' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/fire-event' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist' {
  declare module.exports: any;
}

declare module '@testing-library/react/dist/pure' {
  declare module.exports: any;
}

declare module '@testing-library/react/dont-cleanup-after-each' {
  declare module.exports: any;
}

declare module '@testing-library/react/pure' {
  declare module.exports: any;
}

// Filename aliases
declare module '@testing-library/react/dist/@testing-library/react.cjs.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.cjs'>;
}
declare module '@testing-library/react/dist/@testing-library/react.esm.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.esm'>;
}
declare module '@testing-library/react/dist/@testing-library/react.pure.cjs.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.pure.cjs'>;
}
declare module '@testing-library/react/dist/@testing-library/react.pure.esm.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.pure.esm'>;
}
declare module '@testing-library/react/dist/@testing-library/react.pure.umd.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.pure.umd'>;
}
declare module '@testing-library/react/dist/@testing-library/react.pure.umd.min.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.pure.umd.min'>;
}
declare module '@testing-library/react/dist/@testing-library/react.umd.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.umd'>;
}
declare module '@testing-library/react/dist/@testing-library/react.umd.min.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/@testing-library/react.umd.min'>;
}
declare module '@testing-library/react/dist/act-compat.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/act-compat'>;
}
declare module '@testing-library/react/dist/fire-event.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/fire-event'>;
}
declare module '@testing-library/react/dist/index' {
  declare module.exports: $Exports<'@testing-library/react/dist'>;
}
declare module '@testing-library/react/dist/index.js' {
  declare module.exports: $Exports<'@testing-library/react/dist'>;
}
declare module '@testing-library/react/dist/pure.js' {
  declare module.exports: $Exports<'@testing-library/react/dist/pure'>;
}
declare module '@testing-library/react/dont-cleanup-after-each.js' {
  declare module.exports: $Exports<'@testing-library/react/dont-cleanup-after-each'>;
}
declare module '@testing-library/react/pure.js' {
  declare module.exports: $Exports<'@testing-library/react/pure'>;
}
