#!/usr/bin/env node

/* eslint-env node */
/* eslint no-console:0 */

const PRELUDE = `/*
This file was generated by running

  $ ./scripts/row.js > packages/gestalt/src/Row.css

*/`;

const BOINT_SIZE_PX = 4;
const SCALE_LENGTH = 12;
const SCALE = new Array(SCALE_LENGTH).fill().map((_, i) => i + 1);

// --

const bt = n => `calc(var(--g-boint) * ${n} / 2)`;
const block = str =>
  [
    '{',
    str
      .split('\n')
      .map(line => (line.length === 0 ? '' : `  ${line}`))
      .join('\n'),
    '}',
  ].join('\n');

const Declaration = ({ property, value }) => `${property}: ${value};`;

const Ruleset = ({ selector, declarations }) =>
  `${selector} ${block(
    Object.keys(declarations)
      .map(property => Declaration({ property, value: declarations[property] }))
      .join('\n')
  )}`;

const Stylesheet = statements =>
  [PRELUDE].concat(statements.map(Ruleset)).join('\n\n');

// --

const ruleset = (selector, declarations) => ({
  selector,
  declarations,
});

const rules = i => [
  // Negative margins on parents
  ruleset(`.horizontalGap${i}`, {
    'margin-left': `${bt(-i)}`,
    'margin-right': `${bt(-i)}`,
  }),
  // Gap padding on children
  ruleset(`.horizontalGap${i} > *`, {
    'padding-left': bt(i),
    'padding-right': bt(i),
  }),
];

console.log(
  Stylesheet([
    ruleset(':root', {
      '--g-boint': `${BOINT_SIZE_PX}px`,
    }),
    ruleset('.row', {
      'align-items': 'center', // default
      display: 'flex',
      'flex-direction': 'row',
      'justify-content': 'flex-start', // default
    }),

    // Add rules for boints 0 through 12
    ...[0, ...SCALE].reduce((arr, i) => arr.concat(rules(i)), []),
  ])
);
