// flow-typed signature: 3de1e93a8724efcd711e0a9dc3674f4b
// flow-typed version: <<STUB>>/@actions/core_v^1.2.5/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@actions/core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@actions/core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@actions/core/lib/command' {
  declare module.exports: any;
}

declare module '@actions/core/lib/core' {
  declare module.exports: any;
}

// Filename aliases
declare module '@actions/core/lib/command.js' {
  declare module.exports: $Exports<'@actions/core/lib/command'>;
}
declare module '@actions/core/lib/core.js' {
  declare module.exports: $Exports<'@actions/core/lib/core'>;
}
