// flow-typed signature: 8822fcd0b72192344eab29ea6124e484
// flow-typed version: <<STUB>>/@actions/github_v^4.0.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@actions/github'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@actions/github' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@actions/github/lib/context' {
  declare module.exports: any;
}

declare module '@actions/github/lib/github' {
  declare module.exports: any;
}

declare module '@actions/github/lib/interfaces' {
  declare module.exports: any;
}

declare module '@actions/github/lib/internal/utils' {
  declare module.exports: any;
}

declare module '@actions/github/lib/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@actions/github/lib/context.js' {
  declare module.exports: $Exports<'@actions/github/lib/context'>;
}
declare module '@actions/github/lib/github.js' {
  declare module.exports: $Exports<'@actions/github/lib/github'>;
}
declare module '@actions/github/lib/interfaces.js' {
  declare module.exports: $Exports<'@actions/github/lib/interfaces'>;
}
declare module '@actions/github/lib/internal/utils.js' {
  declare module.exports: $Exports<'@actions/github/lib/internal/utils'>;
}
declare module '@actions/github/lib/utils.js' {
  declare module.exports: $Exports<'@actions/github/lib/utils'>;
}
