// flow-typed signature: e6685219b619aa72b5ded8e876381bb4
// flow-typed version: <<STUB>>/@floating-ui/react_v0.25.4/flow_v0.210.2

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@floating-ui/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@floating-ui/react' {
  declare module.exports: any;

  declare type Alignment = 'start' | 'end';
  declare type Side = 'top' | 'right' | 'bottom' | 'left';
  declare type AlignedPlacement = "top-start" | "top-end" | "right-start" | "right-end" | "bottom-start" | "bottom-end" | "left-start" | "left-end";
  declare type Placement = Side | AlignedPlacement;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@floating-ui/react/dist/floating-ui.react.esm' {
  declare module.exports: any;
}

declare module '@floating-ui/react/dist/floating-ui.react.esm.min' {
  declare module.exports: any;
}

declare module '@floating-ui/react/dist/floating-ui.react.umd' {
  declare module.exports: any;
}

declare module '@floating-ui/react/dist/floating-ui.react.umd.min' {
  declare module.exports: any;
}

// Filename aliases
declare module '@floating-ui/react/dist/floating-ui.react.esm.js' {
  declare module.exports: $Exports<'@floating-ui/react/dist/floating-ui.react.esm'>;
}
declare module '@floating-ui/react/dist/floating-ui.react.esm.min.js' {
  declare module.exports: $Exports<'@floating-ui/react/dist/floating-ui.react.esm.min'>;
}
declare module '@floating-ui/react/dist/floating-ui.react.umd.js' {
  declare module.exports: $Exports<'@floating-ui/react/dist/floating-ui.react.umd'>;
}
declare module '@floating-ui/react/dist/floating-ui.react.umd.min.js' {
  declare module.exports: $Exports<'@floating-ui/react/dist/floating-ui.react.umd.min'>;
}
