// flow-typed signature: 106a88f5cd35e6b0ffcb98949166cfb8
// flow-typed version: <<STUB>>/@rollup/plugin-json_v^4.1.0/flow_v0.127.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@rollup/plugin-json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@rollup/plugin-json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@rollup/plugin-json/dist/index.es' {
  declare module.exports: any;
}

declare module '@rollup/plugin-json/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module '@rollup/plugin-json/dist/index.es.js' {
  declare module.exports: $Exports<'@rollup/plugin-json/dist/index.es'>;
}
declare module '@rollup/plugin-json/dist/index' {
  declare module.exports: $Exports<'@rollup/plugin-json/dist'>;
}
declare module '@rollup/plugin-json/dist/index.js' {
  declare module.exports: $Exports<'@rollup/plugin-json/dist'>;
}
