// flow-typed signature: fbbdc3fd4e6ebe02065991c643269bab
// flow-typed version: <<STUB>>/@codesandbox/sandpack-react_v1.2.4/flow_v0.178.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@codesandbox/sandpack-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@codesandbox/sandpack-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@codesandbox/sandpack-react/dist/cjs' {
  declare module.exports: any;
}

declare module '@codesandbox/sandpack-react/dist/cjs/types' {
  declare module.exports: any;
}

declare module '@codesandbox/sandpack-react/dist/esm' {
  declare module.exports: any;
}

declare module '@codesandbox/sandpack-react/dist/esm/types' {
  declare module.exports: any;
}

// Filename aliases
declare module '@codesandbox/sandpack-react/dist/cjs/index' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/cjs'>;
}
declare module '@codesandbox/sandpack-react/dist/cjs/index.js' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/cjs'>;
}
declare module '@codesandbox/sandpack-react/dist/cjs/types.js' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/cjs/types'>;
}
declare module '@codesandbox/sandpack-react/dist/esm/index' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/esm'>;
}
declare module '@codesandbox/sandpack-react/dist/esm/index.js' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/esm'>;
}
declare module '@codesandbox/sandpack-react/dist/esm/types.js' {
  declare module.exports: $Exports<'@codesandbox/sandpack-react/dist/esm/types'>;
}
