name: Format Files
on:
  pull_request:
    branches: [master]
permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run Formatter
        run: yarn format

      - name: Commit changes
        run: |
          git add -A
          git commit -m "Applying Formatting Changes"
          git push
