name: Integration Tests
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      # when one test fails, DO NOT cancel the other
      # containers, because this will kill Cypress processes
      # leaving the Dashboard hanging ...
      # https://github.com/cypress-io/github-action/issues/48
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: yarn build
          start: yarn docs
          wait-on: 'http://localhost:3000'
          group: ci
          record: true
          parallel: true
          # tag will be either "push" or "pull_request"
          tag: ${{ github.event_name }}
        env:
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }}
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: 'b63ae79f-fb3e-439f-b588-4946a6593370'
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
