name: Visual Test (Playwright)
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  playwright-run:
    name: Test (${{ matrix.shard }})
    timeout-minutes: 60
    runs-on: macos-latest-xlarge
    strategy:
      fail-fast: false
      matrix:
        shard: ['1/5', '2/5', '3/5', '4/5', '5/5']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Build
        run: yarn build
      - name: Run your tests
        id: results
        uses: mathiasvr/command-output@v2.0.0
        with:
          run: yarn run playwright:visual-test --workers 2 --reporter=dot --shard=${{ matrix.shard }}
      - name: Comment PR with execution number
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.results.outputs.stdout }}
          comment_tag: visual-test
